apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: app-prod
data:
  DATABASE_HOST: postgres
  DATABASE_PORT: "5432"
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: app-prod
type: Opaque
data:
  POSTGRES_PASSWORD: c2VuaGExMjM=  # senha base64 de senha "senha123"
