apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-html
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/nginx-html
