apiVersion: v1
kind: Pod
metadata:
  name: web-com-logger
spec:
  containers:
    - name: nginx-web
      image: nginx
      volumeMounts:
        - name: log-volume
          mountPath: /var/log/nginx
    - name: log-sidecar
      image: busybox
      command: ["/bin/sh", "-c", "tail -n+1 -F /var/log/nginx/access.log"]
      volumeMounts:
        - name: log-volume
          mountPath: /var/log/nginx
  volumes:
    - name: log-volume
      emptyDir: {}
