apiVersion: v1
kind: Pod
metadata:
  name: adapter-pod
spec:
  containers:
    - name: producer
      image: busybox
      command: ["/bin/sh", "-c"]
      args:
        - while true; do echo "minha_metrica_customizada 42" > /metrics/raw.metrics; sleep 5; done
      volumeMounts:
        - name: metrics-volume
          mountPath: /metrics
    - name: metrics-adapter
      image: python:3.9-slim
      command: ["python3", "-m", "http.server", "9100"]
      workingDir: /metrics
      volumeMounts:
        - name: metrics-volume
          mountPath: /metrics
  volumes:
    - name: metrics-volume
      emptyDir: {}
