apiVersion: v1
kind: Pod
metadata:
  name: pod-com-recursos
spec:
  containers:
    - name: app
      image: busybox
      command: ["/bin/sh", "-c", "while true; do echo Trabalhando...; sleep 10; done"]
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
