apiVersion: v1
kind: Pod
metadata:
  name: webapp-final
spec:
  containers:
    - name: nginx
      image: nginx
      lifecycle:
        postStart:
          exec:
            command: ["/bin/sh", "-c", "echo 'Iniciado em: ' $(date) >> /var/log/nginx/start.log"]
        preStop:
          exec:
            command: ["/bin/sh", "-c", "echo 'Encerrando em: ' $(date) >> /var/log/nginx/stop.log"]
      volumeMounts:
        - name: log-volume
          mountPath: /var/log/nginx
    - name: log-sidecar
      image: busybox
      command: ["/bin/sh", "-c", "tail -n+1 -F /var/log/nginx/*.log"]
      volumeMounts:
        - name: log-volume
          mountPath: /var/log/nginx