apiVersion: v1
kind: Pod
metadata:
  name: pod-multicontainer
spec:
  containers:
    - name: writer
      image: busybox
      command: ["/bin/sh", "-c"]
      args:
        - |
          echo "Ambiente: $AMBIENTE" > /shared/relatorio.txt;
          echo "Nível de log: $NIVEL_LOG" >> /shared/relatorio.txt;
          echo "Usuário: $USUARIO" >> /shared/relatorio.txt;
          echo "Senha: $SENHA" >> /shared/relatorio.txt;
          sleep 3600;
      env:
        - name: AMBIENTE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: ambiente
        - name: NIVEL_LOG
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: nivel_log
        - name: USUARIO
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: usuario
        - name: SENHA
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: senha
      volumeMounts:
        - name: shared-volume
          mountPath: /shared

    - name: reader
      image: busybox
      command: ["/bin/sh", "-c"]
      args:
        - tail -f /shared/relatorio.txt;
      volumeMounts:
        - name: shared-volume
          mountPath: /shared

  volumes:
    - name: shared-volume
      emptyDir: {}
