apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-app
  labels:
    app: web
    tier: frontend
    environment: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
        tier: frontend
        environment: dev
    spec:
      containers:
      - name: nginx-container
        image: nginx:wrongtag  # erro proposital
        ports:
        - containerPort: 80
